version: '2'
services:
    postgres:
        image: postgres
        restart: always
        expose:
            - "5432"
        networks:
            - default
    rabbitmq:
        restart: always
        image: rabbitmq:3
        expose:
            - "5672"
        networks:
            - default
    consumer:
        restart: always
        build: ./consumer
        links:
            - rabbitmq
            - postgres
        networks:
            - default
